DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS SOLUTION_RESULTS;

CREATE TABLE DEPARTMENT (
  DEPARTMENT_ID INT PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(100)
);

CREATE TABLE EMPLOYEE (
  EMP_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  DOB DATE,
  GENDER VARCHAR(10),
  DEPARTMENT INT,
  CONSTRAINT FK_DEPT FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE PAYMENTS (
  PAYMENT_ID INT PRIMARY KEY,
  EMP_ID INT,
  AMOUNT DECIMAL(15,2),
  PAYMENT_TIME TIMESTAMP,
  CONSTRAINT FK_EMP_PAY FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

CREATE TABLE SOLUTION_RESULTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SALARY DECIMAL(15,2),
  NAME VARCHAR(200),
  AGE INT,
  DEPARTMENT_NAME VARCHAR(100)
);
